apiVersion : apps/v1
kind: Deployment
metadata:
  name: molnardangitaksdash-deploy 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: molnardangitaksdash-deploy
  template:
    metadata:
      labels:
        app: molnardangitaksdash-deploy
    spec:
      containers:
        - name: molnardangitaksdash-container
          image: molnadaaksregistry.azurecr.io/molnardangitaksdash
          ports:
          - containerPort: 80
