apiVersion: v1
kind: Service
metadata:
    name: molnardangitaksdash-svc
spec:
    type: LoadBalancer
    ports:
    - port: 80 
      targetport: 80
    selector:
        app: molnardangitaksdash-deploy