apiVersion: v1
kind: Service
metadata:
    name: molnardangitaksdash-svc
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 8050
    selector:
        app: molnardangitaksdash-deploy